### ISSUE TITLE
Registre a la Seu de la Generalitat a Girona

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#13]
es pot fer [online](http://justicia.gencat.cat/ca/tramits/tramits-temes/Constitucio-duna-associacio?category=753ac520-a82c-11e3-a972-000c29052e2c)

alt: anar a l'Oficina d'Atenció Ciutadana de la Delegació Territorial de la Generalitat de Catalunya a Girona

**Comment by victormartingarcia** [comment]
Sembla que necessitem que la associació estigui formalment constituida. Segons https://www2.girona.cat/ca/entitats/registre necessitem aportar:

- Còpia de la resolució del Registre General d'Associacions de la Generalitat de Catalunya
- Còpia compulsada dels estatuts actuals de l'entitat, o original i còpia
- Junta directiva actualitzada, amb els noms, adreces i telèfons dels/les membres
- Fotocòpia del NIF de l'entitat
- Programa d'activitats realitzades durant l'any
- Pressupost de l'any en curs
- Certificat del nombre de socis i sòcies que té l'entitat
- Logotip de l'entitat, en cas de tenir-ne algun

**Comment by XaviTorello** [comment]
Sorry @victormartingarcia és un duplicat de #12 (la que va tirar endavant en @jbagot). T'assigno la correcta
