### ISSUE TITLE
Inscripció al Registre Municipal d'Entitats

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#14]
https://seu.girona.cat/portal/girona_ca/serveis/e-registre/AaZ/1360.html

**Comment by XaviTorello** [comment]
Em sembla que podriem reactivar aquesta tasca ara que hem tancat #12, com ho veus @victormartingarcia?

**Comment by XaviTorello** [comment]
ping @victormartingarcia

**Comment by victormartingarcia** [comment]
Un cop inscrits en el Registre General d'Associacions de la Generalitat, necessitem emplenar un qüestionari de l'ajgi i presentar:

- Fotocòpia del NIF (definitiu)
- Pressupost de l'entitat durant l'any 2020
- Programa d'activitats a Girona ciutat durant l'any 2020

Es pot tramitar online amb el certificat digital: https://seu.girona.cat/portal/girona_ca/serveis/e-registre/AaZ/1360.html

**Comment by jbagot** [comment]
Està fet
