### ISSUE TITLE
NIF provisional i l'exempció de l'IVA

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#15]
Lloc: Delegació d'Hisenda de Girona

http://xarxanet.org/economic/recursos/com-demanar-el-nif-per-primer-cop

**Comment by jbagot** [comment]
Tinc hora el dimecres al mig dia, ja tinc tots els papers.

**Comment by jbagot** [comment]
Ja tenim el NIF provisional, teniu tots els fitxers escanejats al drive.

**Comment by XaviTorello** [comment]
Tanco issue, ja n'obrirem una quan puguem fer la sol·licitud per a que sigui definitiu i poder optar a l'exempció de l'IVA

Gràcies @jbagot :beers:
