### ISSUE TITLE
Votació: Afegim IBAN al form d'alta de socis?

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#19]
Potser valdria la pena integrar l'IBAN al `formulari d'alta de soci`.

Potser com a camp opcional. Crec que és millor captar el soci i després esbarallar-nos per aconseguir l'IBAN que no que sigui obligatori i que perdem possibles socis.

Amb això ens quedaria totalment integrat dins del llistat de socis i simplificarà força la definició de remeses.

### Votació

Afegim IBAN al form d'alta de socis?

### Opcions

- Sí (camp obligatori)
- Sí (camp opcional)
- No
- NS/NC

**Comment by XaviTorello** [comment]
Sí (camp obligatori)

**Comment by XaviTorello** [comment]
Sí (camp opcional)

**Comment by jbagot** [comment]
Sí (camp opcional). Amb missatge indicant que el necessitem i que si no el vol compartir en el formulari se li demanarà per email o per algun altre lloc

**Comment by francescarpi** [comment]
Sí (camp opcional) i em sumo al que diu en Jordi.

**Comment by XaviTorello** [comment]
@victormartingarcia @efarres, com ho veieu?

**Comment by victormartingarcia** [comment]
Si - Em sembla perfecte posar-ho com opcional

**Comment by XaviTorello** [comment]
Tanquem votació: 
- 4 sí (camp opcional)

Afegeixo el camp IBAN al formulari:

![image](https://user-images.githubusercontent.com/8709244/88915619-eb08b380-d264-11ea-8495-b9a7fb185884.png)

Gràcies @GeeksCAT/core :beers:
