### ISSUE TITLE
Video presentació PyGRN per PyConES2020 Pandemic Edition

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#26]
Més info a https://comunidad.es.python.org/t/presentacion-de-comunidades-durante-pycones-2020/330

Deadline 2020/09/15

**Comment by victormartingarcia** [comment]
Primer draft amb la proposta del guió per al video:

https://hackmd.io/nLM-wtqYSq6VyroFRdz8tw
