### ISSUE TITLE
Preparar landing page de l'esdeveniment

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#29]
Valdria la pena preparar una landing page per l'esdeveniment, on puguem explicar:
- què farem
- quan ho farem
- com ho farem
- contacte

No cal matar-nos gaire, val la pena tenir un draft ASAP per poder-ne anar moldejant el contingut

Algunes idees:
- https://github.com/python-spain/hacktoberfestES
- http://html5up.net

**Comment by XaviTorello** [comment]
Com ho veus @francescarpi? Potser podriem forkejar https://hacktoberfest.es.python.org i començar a preparar contingut :)

**Comment by francescarpi** [comment]
Ho veig bé! Avui després de la feina (cap a les 17h) m'hi posaré.

Faré una ullada ràpida al html5up, i si no convenç res, faig el fork.

Gràcis!

**Comment by XaviTorello** [comment]
Ho deia per mantenir una mica la imatge del HTB :)

Ara pensava que si agafem alguna plantilla oberta no tindrem l'estil típic del HTB heheheheh

**Comment by francescarpi** [comment]
Això és cert, i la veritat que està xulo el disseny que tenen. Doncs no em complicaré. Faré fork i treballem sobre aquest. Hem d'anar cara a barraca que no hi ha molt temps :)

**Comment by XaviTorello** [comment]
He forkejat el repo i he deixat la gh-page preparada sota https://hacktoberfest.geekscat.org

He començat la traducció, després mirem el contingut, bàsicament seria explicar que ens focalitzarem en un projecte en concret (el detallem quan ho tinguem confirmat a #30) però que estem oberts a propostes per dinamitzar qualsevol altre projecte. Alhora que tots sóm lliures de col·laborar en qualsevol altre projecte.

M'agrada la idea de fer servir eventbrite o koobin (o similars) per simplificar el registre. Obro issue per estudiar-ho plegats a #33 Eina per gestionar assistència al HTB'20

**Comment by francescarpi** [comment]
He creat pull request 

https://github.com/python-spain/hacktoberfestES/pull/2

**Comment by francescarpi** [comment]
https://github.com/GeeksCAT/hacktoberfest-2020/pull/1
