### ISSUE TITLE
Eina per gestionar assistència al HTB'20

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#33]
M'agrada la idea de fer servir Eventbrite o Koobin (o similars) per simplificar el procés de registre i gestionar l'assistència a l'esdeveniment.

Què en penseu @GeeksCAT/core?

**Comment by francescarpi** [comment]
A mi també m'agrada la idea d'implementar Eventbrite, més que res per què no el conec i així aprenc algo nou. Entenc que és una eina que satisfà completament les nostres necessitats, i al haver-la utilitzat a esdeveniments de Python Espanya, ens dona garanties.

En quan a Koobin, em tira enrere que ens haguem de posar en contacte amb ells i no tinguem la facilitat de fer-ho tot nosaltres online.

Una altra opció seria utilitzar el meetup, que ja la tenim configurada i crear l'esdeveniment serà un moment.

**Comment by XaviTorello** [comment]
Em sembla bona idea contemplar també Meetup 👍

**Comment by XaviTorello** [comment]
Acabo de crear l'esdeveniment a EventBrite: https://www.eventbrite.es/e/entradas-hacktoberfest-geekscat-2020-123187963515

Quan tinguem data, obro Meetup pel Kickoff.

**Comment by XaviTorello** [comment]
Meetup pel Kickoff obert! https://www.meetup.com/PythonGirona/events/273636166

Tanco issue
