### ISSUE TITLE
Sol·licitar NIF definitiu i exempció de l'IVA

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#38]
Ara que ja estem inscrits al registre d'associacions #12, podriem avançar amb això sol·licitant que el NIF sigui definitiu.

Alhora podriem demanar l'exempció de l'IVA

Relacionat amb #15

**Comment by XaviTorello** [comment]
ping @jbagot

@efarres, podríes donar-nos un cop de mà?

**Comment by jbagot** [comment]
Està fet
