### ISSUE TITLE
Procés de domiciliació anual pels socis

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#39]
Relacionat amb #10, caldria confirmar quins són els requeriments i les condicions per poder fer domiciliacions anuals per cobrar les quotes de soci

Concretament:
- Què necessitem per definir-la?
- Periodicitat anual automàtica?
- Comissió <-- intentar forçar cost 0 :)
- Què passa si alguna falla?
- Se'ns fa arribar un llistat del resultat de la remesa, o hem de revisar directament el CC?

**Comment by francescarpi** [comment]
Perfecte! Quan vagi a portar els papers per a crear el compte, aclariré aquests punts.

**Comment by jbagot** [comment]
Això ja està fet.
