### ISSUE TITLE
Dinamitzar la creació d'un hackathon colaboratiu a Girona

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#7]
que aporti algo a la societat en format software lliure + procés open
- @efb-ubikwa proposa apropar-nos a XXX per ajudar-los a crear software que ajudi al tracking anònim de la pandèmia
- old: port a OS de meetup.com
- en pot sortir un GT que mantingui aquest software

**Comment by XaviTorello** [comment]
estudiar la possibilitat de vincular-ho al [Hacktoberfest](https://hacktoberfest.digitalocean.com) (p.e https://hacktoberfestbarcelona.com)

**Comment by jbagot** [comment]
Ho hem fet dues vegades des que es va crear aquesta issue. Al 2020 vam participar al Hacktoberfest amb el projecte `nem per feina` on es van crear equips i vam fer aquesta web per posar en contacte empreses i treballadors del món digital.
Al 2021 vam decidir fer un esdeveniment presencial també enfocat al Hacktoberfest que va ser la 1a Festa de l'Open Source de Girona. Es va fer al centre cultural de la Mercè i es van fer xerrades, un taller d'iniciació a django i una marató de PRs.
