### ISSUE TITLE
Comunicar a PythonGirona la situació actual

### ISSUE THREAD

**Issue by XaviTorello** [GeeksCAT/associacio#9]
Comunicar a PythonGirona la situació actual, missatge
- seguim vius!
- apostem per les trobades presencials, tot i això si algú s’interessa per fer alguna online estarem encantats de rebre propostes
- com cada any farem parón d’estiu
- tornem al setembre!
- keep save :)

**Comment by XaviTorello** [comment]
Com ho veieu @GeeksCAT/core?


Bones Pythonistes!

Només us volíem confirmar que seguim vius i amb moltes ganes de poder reprendre l'activitat de PythonGirona amb la màxima normalitat possible :muscle:.

Com sabreu acabem de constituir l'associació [GeeksCAT](https://geekscat.org), i ben aviat encetarem la [definició del grup de treball PythonGirona](https://github.com/GeeksCAT/associacio/issues/2). Estarem encantats de rebre idees i de que entre tots sumem! En cap cas ni l'essència de PythonGirona ni el cicle de xerrades es veurà alterat :)

Durant el confinament hem tirat endavant algunes iniciatives online, com la xerrada `Go per pythonistes` o la `Primera Jam session pythonica`. Han sorgit algunes idees, però entenem que hi ha força trobades virtuals a disposició de tothom, i on realment podem aportar és en les trobades personals a Girona.

Com cada any, durant els mesos d'estiu _tanquem per vacances_ així que ens **veiem al setembre**!

Esperem que estigueu totes bé i amb ganes de tornar-nos a trobar ben aviat!

Hap.py coding!

--
L'equip de GeeksCAT - PythonGirona

**Comment by jbagot** [comment]
A mi em sembla bé!

**Comment by XaviTorello** [comment]
Missatge enviat a la llista de meetup :+1:
